cask_args appdir: '/Applications'

brew 'coreutils'
brew 'gpg'
brew 'neofetch'
brew 'node'
brew 'pinentry-mac'
brew 'vim'
brew 'zsh'

cask 'hyper'
cask 'the-unarchiver'
cask 'typora'
cask 'visual-studio-code'
